[package]
name = "grezi_layout"
version = "0.1.0"
edition = "2021"

[dependencies]
cassowary = "0.3.0"
emath.workspace = true
itertools = "0.14.0"
smallvec = "1.14.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.24.0"
